--CREATE DATABASE TripPlanner;

USE TripPlanner;

CREATE TABLE Passport (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
PassportNumber NVARCHAR(20) NOT NULL,
ExpirationDate DATE NOT NULL,
Address NVARCHAR(60) NOT NULL
);

CREATE TABLE Users (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
PassportId INT FOREIGN KEY REFERENCES Passport(Id),
FirstName NVARCHAR(20) NOT NULL,
LastName NVARCHAR(20) NOT NULL,
Address NVARCHAR(60) NOT NULL,
PhoneNumber NVARCHAR(25) NOT NULL,
DOB DATE NOT NULL
);

CREATE TABLE Trip (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
UserId INT FOREIGN KEY REFERENCES Users(Id),
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
Budget FLOAT NOT NULL,
StartingDestination NVARCHAR(100) NOT NULL,
EndingDestination NVARCHAR(100) NOT NULL,
TravelMode NVARCHAR(60) NOT NULL
);

CREATE TABLE Hotel (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
HotelName NVARCHAR(50) NOT NULL,
Rating INT NOT NULL,
NightlyCost FLOAT NOT NULL,
Address NVARCHAR(60) NOT NULL,
PhoneNumber NVARCHAR(25) NOT NULL
);

CREATE TABLE TripDetails (
TripId INT FOREIGN KEY REFERENCES Trip(Id),
HotelId INT FOREIGN KEY REFERENCES Hotel(Id),
CheckInDate DATE NOT NULL,
CheckOutDate DATE NOT NULL
);